export type JapanRegion = {code: number, name: string, kana: string, en: string}
export type JapanPref = {code: number, region: number, name: string, short: string, kana: string, enName: string, area: string, capital: string}

export const regs: JapanRegion[] = [
    {code: 1, name: "北海道", kana: "ホッカイドウ", en: "hokkaido"},
    {code: 2, name: "東北", kana: "トウホク", en: "tohoku"},
    {code: 3, name: "関東", kana: "カントウ", en: "kanto"},
    {code: 4, name: "中部", kana: "チュウブ", en: "chubu"},
    {code: 5, name: "近畿", kana: "キンキ", en: "kinki"},
    {code: 6, name: "中国", kana: "チュウゴク", en: "chugoku"},
    {code: 7, name: "四国", kana: "シコク", en: "shikoku"},
    {code: 8, name: "九州", kana: "キュウシュウ", en: "kyusyu"}
];

export const prefs: JapanPref[] = [
    {code: 1, region: 1, name: "北海道", short: "北海道", kana: "ホッカイドウ", enName: "hokkaido", area: "北海道", capital: "札幌市"},
    {code: 2, region: 2, name: "青森県", short: "青森", kana: "アオモリ", enName: "aomori", area: "東北", capital: "青森市"},
    {code: 3, region: 2, name: "岩手県", short: "岩手", kana: "イワテ", enName: "iwate", area: "東北", capital: "盛岡市"},
    {code: 4, region: 2, name: "宮城県", short: "宮城", kana: "ミヤギ", enName: "miyagi", area: "東北", capital: "仙台市"},
    {code: 5, region: 2, name: "秋田県", short: "秋田", kana: "アキタ", enName: "akita", area: "東北", capital: "秋田市"},
    {code: 6, region: 2, name: "山形県", short: "山形", kana: "ヤマガタ", enName: "yamagata", area: "東北", capital: "山形市"},
    {code: 7, region: 2, name: "福島県", short: "福島", kana: "フクシマ", enName: "fukushima", area: "東北", capital: "福島市"},
    {code: 8, region: 3, name: "茨城県", short: "茨城", kana: "イバラキ", enName: "ibaraki", area: "関東", capital: "水戸市"},
    {code: 9, region: 3, name: "栃木県", short: "栃木", kana: "トチギ", enName: "tochigi", area: "関東", capital: "宇都宮市"},
    {code: 10, region: 3, name: "群馬県", short: "群馬", kana: "グンマ", enName: "gunma", area: "関東", capital: "前橋市"},
    {code: 11, region: 3, name: "埼玉県", short: "埼玉", kana: "サイタマ", enName: "saitama", area: "関東", capital: "さいたま市"},
    {code: 12, region: 3, name: "千葉県", short: "千葉", kana: "チバ", enName: "chiba", area: "関東", capital: "千葉市"},
    {code: 13, region: 3, name: "東京都", short: "東京", kana: "トウキョウ", enName: "tokyo", area: "関東", capital: "新宿区"},
    {code: 14, region: 3, name: "神奈川県", short: "神奈川", kana: "カナガワ", enName: "kanagawa", area: "関東", capital: "横浜市"},
    {code: 15, region: 4, name: "新潟県", short: "新潟", kana: "ニイガタ", enName: "niigata", area: "中部", capital: "新潟市"},
    {code: 16, region: 4, name: "富山県", short: "富山", kana: "トヤマ", enName: "toyama", area: "中部", capital: "富山市"},
    {code: 17, region: 4, name: "石川県", short: "石川", kana: "イシカワ", enName: "ishikawa", area: "中部", capital: "金沢市"},
    {code: 18, region: 4, name: "福井県", short: "福井", kana: "フクイ", enName: "fukui", area: "中部", capital: "福井市"},
    {code: 19, region: 4, name: "山梨県", short: "山梨", kana: "ヤマナシ", enName: "yamanashi", area: "中部", capital: "甲府市"},
    {code: 20, region: 4, name: "長野県", short: "長野", kana: "ナガノ", enName: "nagano", area: "中部", capital: "長野市"},
    {code: 21, region: 4, name: "岐阜県", short: "岐阜", kana: "ギフ", enName: "gifu", area: "中部", capital: "岐阜市"},
    {code: 22, region: 4, name: "静岡県", short: "静岡", kana: "シズオカ", enName: "shizuoka", area: "中部", capital: "静岡市"},
    {code: 23, region: 4, name: "愛知県", short: "愛知", kana: "アイチ", enName: "aichi", area: "中部", capital: "名古屋市"},
    {code: 24, region: 5, name: "三重県", short: "三重", kana: "ミエ", enName: "mie", area: "関西", capital: "津市"},
    {code: 25, region: 5, name: "滋賀県", short: "滋賀", kana: "シガ", enName: "shiga", area: "関西", capital: "大津市"},
    {code: 26, region: 5, name: "京都府", short: "京都", kana: "キョウト", enName: "kyoto", area: "関西", capital: "京都市"},
    {code: 27, region: 5, name: "大阪府", short: "大阪", kana: "オオサカ", enName: "osaka", area: "関西", capital: "大阪市"},
    {code: 28, region: 5, name: "兵庫県", short: "兵庫", kana: "ヒョウゴ", enName: "hyogo", area: "関西", capital: "神戸市"},
    {code: 29, region: 5, name: "奈良県", short: "奈良", kana: "ナラ", enName: "nara", area: "関西", capital: "奈良市"},
    {code: 30, region: 5, name: "和歌山県", short: "和歌山", kana: "ワカヤマ", enName: "wakayama", area: "関西", capital: "和歌山市"},
    {code: 31, region: 6, name: "鳥取県", short: "鳥取", kana: "トットリ", enName: "tottori", area: "中国", capital: "鳥取市"},
    {code: 32, region: 6, name: "島根県", short: "島根", kana: "シマネ", enName: "shimane", area: "中国", capital: "松江市"},
    {code: 33, region: 6, name: "岡山県", short: "岡山", kana: "オカヤマ", enName: "okayama", area: "中国", capital: "岡山市"},
    {code: 34, region: 6, name: "広島県", short: "広島", kana: "ヒロシマ", enName: "hiroshima", area: "中国", capital: "広島市"},
    {code: 35, region: 6, name: "山口県", short: "山口", kana: "ヤマグチ", enName: "yamaguchi", area: "中国", capital: "山口市"},
    {code: 36, region: 7, name: "徳島県", short: "徳島", kana: "トクシマ", enName: "tokushima", area: "四国", capital: "徳島市"},
    {code: 37, region: 7, name: "香川県", short: "香川", kana: "カガワ", enName: "kagawa", area: "四国", capital: "高松市"},
    {code: 38, region: 7, name: "愛媛県", short: "愛媛", kana: "エヒメ", enName: "ehime", area: "四国", capital: "松山市"},
    {code: 39, region: 7, name: "高知県", short: "高知", kana: "コウチ", enName: "kochi", area: "四国", capital: "高知市"},
    {code: 40, region: 8, name: "福岡県", short: "福岡", kana: "フクオカ", enName: "fukuoka", area: "九州", capital: "福岡市"},
    {code: 41, region: 8, name: "佐賀県", short: "佐賀", kana: "サガ", enName: "saga", area: "九州", capital: "佐賀市"},
    {code: 42, region: 8, name: "長崎県", short: "長崎", kana: "ナガサキ", enName: "nagasaki", area: "九州", capital: "長崎市"},
    {code: 43, region: 8, name: "熊本県", short: "熊本", kana: "クマモト", enName: "kumamoto", area: "九州", capital: "熊本市"},
    {code: 44, region: 8, name: "大分県", short: "大分", kana: "オオイタ", enName: "oita", area: "九州", capital: "大分市"},
    {code: 45, region: 8, name: "宮崎県", short: "宮崎", kana: "ミヤザキ", enName: "miyazaki", area: "九州", capital: "宮崎市"},
    {code: 46, region: 8, name: "鹿児島県", short: "鹿児島", kana: "カゴシマ", enName: "kagoshima", area: "九州", capital: "鹿児島市"},
    {code: 47, region: 8, name: "沖縄県", short: "沖縄", kana: "オキナワ", enName: "okinawa", area: "九州", capital: "那覇市"}
];
