version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      network: host
    ports:
      - "3000:3000"
#    volumes:
#      - .:/app
#      - /app/node_modules
#    depends_on:
#      - postgres
#      - mongodb
#      - redis
#    environment:
#      - NODE_ENV=development
    env_file:
      - .env

#  postgres:
#    image: postgres:16-alpine
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=episodify
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#  mongodb:
#    image: mongo:7
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongodb_data:/data/db
#
#  redis:
#    image: redis:7-alpine
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data

#volumes:
#  postgres_data:
#  mongodb_data:
#  redis_data:
